package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const hotspareFile = "workdeck-hotspare.json"
const hotspareLock = "workdeck-hotspare.lock"
const skillMarker = "<!-- Generated by workdeck; do not edit. -->"

type hotspareConfig struct {
	Main   string   `json:"main"`
	Spares []string `json:"spares"`
	Base   string   `json:"base"`
}

type hotspareState struct {
	Claimed    bool      `json:"claimed"`
	Branch     string    `json:"branch,omitempty"`
	Base       string    `json:"base"`
	BaseCommit string    `json:"baseCommit,omitempty"`
	ClaimedAt  time.Time `json:"claimedAt,omitempty"`
	Host       string    `json:"host,omitempty"`
	PID        int       `json:"pid,omitempty"`
}

func canonicalDir(path string) (string, error) {
	path, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	path, err = filepath.EvalSymlinks(path)
	if err != nil {
		return "", err
	}
	info, err := os.Stat(path)
	if err != nil {
		return "", err
	}
	if !info.IsDir() {
		return "", fmt.Errorf("not a directory: %s", path)
	}
	return path, nil
}

func gitDir(path string) (string, error) {
	info, err := os.Stat(filepath.Join(path, ".git"))
	if err != nil {
		return "", fmt.Errorf("%s is not an independent Git checkout: %w", path, err)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("%s must have a .git directory, not a linked worktree", path)
	}
	return filepath.Join(path, ".git"), nil
}

func git(path string, args ...string) (string, error) {
	cmd := exec.Command("git", append([]string{"-C", path}, args...)...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("git -C %s %s: %w: %s", path, strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return strings.TrimSpace(string(output)), nil
}

func gitOK(path string, args ...string) bool {
	cmd := exec.Command("git", append([]string{"-C", path}, args...)...)
	return cmd.Run() == nil
}

func readJSON(path string, value any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, value)
}

func writeJSON(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(path, data, 0600)
}

func configPath(main string) (string, error) {
	d, err := gitDir(main)
	return filepath.Join(d, hotspareFile), err
}
func statePath(spare string) (string, error) {
	d, err := gitDir(spare)
	return filepath.Join(d, hotspareFile), err
}
func lockPath(spare string) (string, error) {
	d, err := gitDir(spare)
	return filepath.Join(d, hotspareLock), err
}

func loadConfig(main string) (hotspareConfig, error) {
	main, err := canonicalDir(main)
	if err != nil {
		return hotspareConfig{}, err
	}
	path, err := configPath(main)
	if err != nil {
		return hotspareConfig{}, err
	}
	var config hotspareConfig
	if err := readJSON(path, &config); err != nil {
		return hotspareConfig{}, fmt.Errorf("read hotspare config: %w", err)
	}
	if config.Main != main {
		return hotspareConfig{}, fmt.Errorf("hotspare config does not belong to %s", main)
	}
	return config, nil
}

func loadState(spare string) (hotspareState, error) {
	path, err := statePath(spare)
	if err != nil {
		return hotspareState{}, err
	}
	var state hotspareState
	if err := readJSON(path, &state); err != nil {
		return hotspareState{}, err
	}
	return state, nil
}

func localBase(base string) string {
	return strings.TrimPrefix(base, "origin/")
}

func (a app) hotspare(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: workdeck hostspare setup [--base <ref>] <main> <spare>... | status --main <main> | claim --main <main> <branch> | release --main <main> <spare> | recover --main <main> <spare> --force")
	}
	if args[0] == "--help" || args[0] == "-h" {
		fmt.Println("usage: workdeck hostspare setup [--base <ref>] <main> <spare>... | status --main <main> | claim --main <main> <branch> | release --main <main> <spare> | recover --main <main> <spare> --force")
		return nil
	}
	switch args[0] {
	case "setup":
		return a.setupHotspares(args[1:])
	case "status":
		main, rest, err := mainFlag(args[1:])
		if err != nil {
			return err
		}
		if len(rest) != 0 {
			return errors.New("status accepts only --main")
		}
		return printHotspareStatus(main)
	case "claim":
		main, rest, err := mainFlag(args[1:])
		if err != nil {
			return err
		}
		if len(rest) != 1 {
			return errors.New("usage: workdeck hostspare claim --main <main> <branch>")
		}
		return claimHotspare(main, rest[0])
	case "release":
		main, rest, err := mainFlag(args[1:])
		if err != nil {
			return err
		}
		if len(rest) != 1 {
			return errors.New("usage: workdeck hostspare release --main <main> <spare>")
		}
		return releaseHotspare(main, rest[0])
	case "recover":
		main, rest, err := mainFlag(args[1:])
		if err != nil {
			return err
		}
		if len(rest) != 2 || rest[1] != "--force" {
			return errors.New("usage: workdeck hostspare recover --main <main> <spare> --force")
		}
		return recoverHotspare(main, rest[0])
	default:
		return fmt.Errorf("unknown hotspare command %q", args[0])
	}
}

func mainFlag(args []string) (string, []string, error) {
	if len(args) < 2 || args[0] != "--main" {
		return "", nil, errors.New("--main <path> is required")
	}
	return args[1], args[2:], nil
}

func (a app) setupHotspares(args []string) error {
	base := ""
	if len(args) >= 2 && args[0] == "--base" {
		base, args = args[1], args[2:]
	}
	if len(args) < 2 {
		return errors.New("usage: workdeck hotspare setup [--base <ref>] <main> <spare>...")
	}
	main, err := canonicalDir(args[0])
	if err != nil {
		return err
	}
	if _, err := gitDir(main); err != nil {
		return err
	}
	branch, err := git(main, "branch", "--show-current")
	if err != nil {
		return err
	}
	if base == "" {
		if branch != "master" {
			return errors.New("--base is required when main is not on master")
		}
		base = "origin/master"
	}
	origin, err := git(main, "remote", "get-url", "origin")
	if err != nil {
		return err
	}
	config := hotspareConfig{Main: main, Base: base}
	seen := map[string]bool{main: true}
	for _, raw := range args[1:] {
		spare, err := canonicalDir(raw)
		if err != nil {
			return err
		}
		if seen[spare] {
			return fmt.Errorf("duplicate hotspare: %s", spare)
		}
		seen[spare] = true
		if _, err := gitDir(spare); err != nil {
			return err
		}
		spareOrigin, err := git(spare, "remote", "get-url", "origin")
		if err != nil {
			return err
		}
		if spareOrigin != origin {
			return fmt.Errorf("%s origin differs from main", spare)
		}
		status, err := git(spare, "status", "--porcelain")
		if err != nil {
			return err
		}
		if status != "" {
			return fmt.Errorf("%s has uncommitted changes", spare)
		}
		config.Spares = append(config.Spares, spare)
	}
	if existing, err := loadConfig(main); err == nil {
		requested := map[string]bool{}
		for _, spare := range config.Spares {
			requested[spare] = true
		}
		for _, spare := range existing.Spares {
			if requested[spare] {
				continue
			}
			state, stateErr := loadState(spare)
			if stateErr != nil {
				return fmt.Errorf("cannot remove configured hotspare %s: %w", spare, stateErr)
			}
			if state.Claimed {
				return fmt.Errorf("refusing to remove claimed hotspare %s", spare)
			}
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := a.checkSkillOverwrite(main, false); err != nil {
		return err
	}
	path, err := configPath(main)
	if err != nil {
		return err
	}
	if err := writeJSON(path, config); err != nil {
		return err
	}
	for _, spare := range config.Spares {
		statePath, err := statePath(spare)
		if err != nil {
			return err
		}
		state := hotspareState{Base: base}
		if old, err := loadState(spare); err == nil && old.Claimed {
			state = old
			state.Base = base
		}
		if err := writeJSON(statePath, state); err != nil {
			return fmt.Errorf("wrote main config but could not write %s: %w", spare, err)
		}
	}
	return a.installSkill(main, false)
}

func available(spare string, config hotspareConfig) (string, bool) {
	state, err := loadState(spare)
	if err != nil {
		return err.Error(), false
	}
	if state.Claimed {
		return "claimed: " + state.Branch, false
	}
	lock, err := lockPath(spare)
	if err != nil {
		return err.Error(), false
	}
	if _, err := os.Stat(lock); err == nil {
		return "locked", false
	}
	status, err := git(spare, "status", "--porcelain")
	if err != nil || status != "" {
		return "dirty", false
	}
	branch, err := git(spare, "branch", "--show-current")
	if err != nil || branch != localBase(config.Base) {
		return "not on " + localBase(config.Base), false
	}
	baseCommit, err := git(spare, "rev-parse", config.Base)
	if err != nil {
		return "cannot resolve " + config.Base, false
	}
	head, err := git(spare, "rev-parse", "HEAD")
	if err != nil || head != baseCommit {
		return "not aligned with " + config.Base, false
	}
	return "available", true
}

func printHotspareStatus(main string) error {
	config, err := loadConfig(main)
	if err != nil {
		return err
	}
	for _, spare := range config.Spares {
		reason, _ := available(spare, config)
		fmt.Printf("%s: %s\n", spare, reason)
	}
	return nil
}

func claimHotspare(main, branch string) error {
	config, err := loadConfig(main)
	if err != nil {
		return err
	}
	if strings.TrimSpace(branch) == "" || strings.HasPrefix(branch, "-") {
		return errors.New("invalid branch name")
	}
	if _, err := git(config.Main, "check-ref-format", "--branch", branch); err != nil {
		return fmt.Errorf("invalid branch %q", branch)
	}
	if _, err := git(config.Main, "fetch", "origin"); err != nil {
		return err
	}
	if gitOK(config.Main, "show-ref", "--verify", "--quiet", "refs/remotes/origin/"+branch) {
		return fmt.Errorf("branch %s already exists on origin", branch)
	}
	for _, path := range append([]string{config.Main}, config.Spares...) {
		current, err := git(path, "branch", "--show-current")
		if err == nil && current == branch {
			return fmt.Errorf("branch %s is checked out at %s", branch, path)
		}
	}
	baseCommit, err := git(config.Main, "rev-parse", "HEAD")
	if err != nil {
		return err
	}
	var blocked []string
	for _, spare := range config.Spares {
		if _, err := git(spare, "fetch", "origin"); err != nil {
			blocked = append(blocked, spare+": fetch failed")
			continue
		}
		if reason, ok := available(spare, config); !ok {
			blocked = append(blocked, spare+": "+reason)
			continue
		}
		lock, err := lockPath(spare)
		if err != nil {
			return err
		}
		file, err := os.OpenFile(lock, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
		if errors.Is(err, os.ErrExist) {
			blocked = append(blocked, spare+": locked")
			continue
		}
		if err != nil {
			return err
		}
		file.Close()
		if _, err := git(spare, "checkout", "-b", branch, baseCommit); err != nil {
			os.Remove(lock)
			return err
		}
		host, _ := os.Hostname()
		statePath, err := statePath(spare)
		if err != nil {
			return err
		}
		state := hotspareState{Claimed: true, Branch: branch, Base: config.Base, BaseCommit: baseCommit, ClaimedAt: time.Now().UTC(), Host: host, PID: os.Getpid()}
		if err := writeJSON(statePath, state); err != nil {
			return err
		}
		fmt.Println(spare)
		return nil
	}
	return fmt.Errorf("no hotspare available; %s", strings.Join(blocked, "; "))
}

func selectSpare(config hotspareConfig, value string) (string, error) {
	for _, spare := range config.Spares {
		if value == spare || value == filepath.Base(spare) {
			return spare, nil
		}
	}
	return "", fmt.Errorf("not a configured hotspare: %s", value)
}

func releaseHotspare(main, value string) error {
	config, err := loadConfig(main)
	if err != nil {
		return err
	}
	spare, err := selectSpare(config, value)
	if err != nil {
		return err
	}
	state, err := loadState(spare)
	if err != nil {
		return err
	}
	if !state.Claimed {
		return fmt.Errorf("%s is not claimed", spare)
	}
	status, err := git(spare, "status", "--porcelain")
	if err != nil {
		return err
	}
	if status != "" {
		return fmt.Errorf("%s has uncommitted changes", spare)
	}
	if _, err := git(spare, "fetch", "origin"); err != nil {
		return err
	}
	if !gitOK(spare, "show-ref", "--verify", "--quiet", "refs/remotes/origin/"+state.Branch) {
		return fmt.Errorf("%s has not been pushed to origin", state.Branch)
	}
	pending, err := git(spare, "rev-list", "--count", "origin/"+state.Branch+".."+state.Branch)
	if err != nil {
		return err
	}
	if pending != "0" {
		return fmt.Errorf("%s has unpushed commits", state.Branch)
	}
	if !gitOK(spare, "merge-base", "--is-ancestor", state.Branch, config.Base) {
		return fmt.Errorf("%s is not merged into %s", state.Branch, config.Base)
	}
	if _, err := git(spare, "checkout", localBase(config.Base)); err != nil {
		return err
	}
	if _, err := git(spare, "merge", "--ff-only", config.Base); err != nil {
		return err
	}
	statePath, err := statePath(spare)
	if err != nil {
		return err
	}
	lock, err := lockPath(spare)
	if err != nil {
		return err
	}
	if err := os.Remove(statePath); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.Remove(lock); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return writeJSON(statePath, hotspareState{Base: config.Base})
}

func recoverHotspare(main, value string) error {
	config, err := loadConfig(main)
	if err != nil {
		return err
	}
	spare, err := selectSpare(config, value)
	if err != nil {
		return err
	}
	status, err := git(spare, "status", "--short", "--branch")
	if err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, status)
	statePath, err := statePath(spare)
	if err != nil {
		return err
	}
	lock, err := lockPath(spare)
	if err != nil {
		return err
	}
	if err := os.Remove(statePath); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.Remove(lock); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return writeJSON(statePath, hotspareState{Base: config.Base})
}

func activeHotspares(projects []entry) ([]entry, error) {
	var configs []hotspareConfig
	for _, project := range projects {
		path, err := configPath(project.path)
		if err != nil {
			continue
		}
		var config hotspareConfig
		if err := readJSON(path, &config); errors.Is(err, os.ErrNotExist) {
			continue
		} else if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		if config.Main == project.path {
			configs = append(configs, config)
		}
	}
	spares := map[string]bool{}
	var active []entry
	for _, config := range configs {
		for _, spare := range config.Spares {
			spares[spare] = true
			state, err := loadState(spare)
			if err != nil {
				return nil, err
			}
			if state.Claimed {
				active = append(active, entry{kind: "hotspare", name: filepath.Base(spare) + " [" + state.Branch + "]", path: spare})
			}
		}
	}
	var filtered []entry
	for _, project := range projects {
		if !spares[project.path] {
			filtered = append(filtered, project)
		}
	}
	sort.Slice(active, func(i, j int) bool { return active[i].path > active[j].path })
	return append(filtered, active...), nil
}

func (a app) skill(args []string) error {
	if len(args) == 0 || args[0] != "install" {
		return errors.New("usage: workdeck skill install --main <main> [--force]")
	}
	main, rest, err := mainFlag(args[1:])
	if err != nil {
		return err
	}
	force := len(rest) == 1 && rest[0] == "--force"
	if len(rest) != 0 && !force {
		return errors.New("usage: workdeck skill install --main <main> [--force]")
	}
	return a.installSkill(main, force)
}

func (a app) installSkill(main string, force bool) error {
	config, err := loadConfig(main)
	if err != nil {
		return err
	}
	if err := a.checkSkillOverwrite(config.Main, force); err != nil {
		return err
	}
	path := a.skillPath(config.Main)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	name := "workdeck-" + filepath.Base(config.Main)
	digest := sha256.Sum256([]byte(config.Main))
	content := fmt.Sprintf("---\nname: %s\ndescription: Use when investigating or editing the managed %s repository. Investigate in main; claim a hostspare before any edit.\n---\n\n%s\n# Workdeck hostspares: %s\n\nInvestigate and plan in `%s`. Before any edit, claim a spare:\n\n```sh\nworkdeck hostspare claim --main %s <branch>\n```\n\nWork only in the printed path. If claiming fails, run `workdeck hostspare status --main %s`, report the unavailable spares, and wait. Do not edit the main checkout. Release only after the branch is pushed and merged:\n\n```sh\nworkdeck hostspare release --main %s <spare>\n```\n\nManaged-set id: %s\n", name, filepath.Base(config.Main), skillMarker, filepath.Base(config.Main), config.Main, config.Main, config.Main, config.Main, hex.EncodeToString(digest[:8]))
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return err
	}
	return a.linkOpenCodeSkill(name, path, force)
}

func (a app) skillPath(main string) string {
	name := "workdeck-" + filepath.Base(main)
	return filepath.Join(a.home, ".agents", "skills", name, "SKILL.md")
}

func (a app) openCodeSkillPath(main string) string {
	name := "workdeck-" + filepath.Base(main)
	return filepath.Join(a.home, ".config", "opencode", "skills", name, "SKILL.md")
}

// OpenCode v1 only scans ~/.config/opencode/skills. Newer OpenCode versions
// also scan ~/.agents/skills, so link both locations to one generated skill.
func (a app) linkOpenCodeSkill(name, source string, force bool) error {
	path := filepath.Join(a.home, ".config", "opencode", "skills", name, "SKILL.md")
	info, err := os.Lstat(path)
	if err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			target, linkErr := os.Readlink(path)
			if linkErr != nil {
				return linkErr
			}
			if target == source {
				return nil
			}
		}
		if !force {
			return fmt.Errorf("refusing to overwrite existing OpenCode skill %s; use workdeck skill install --main <main> --force", path)
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.Symlink(source, path)
}

func (a app) checkSkillOverwrite(main string, force bool) error {
	path := a.skillPath(main)
	if old, err := os.ReadFile(path); err == nil && !strings.Contains(string(old), skillMarker) && !force {
		return fmt.Errorf("refusing to overwrite manually changed skill %s; use workdeck skill install --main %s --force", path, main)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	openCodePath := a.openCodeSkillPath(main)
	if info, err := os.Lstat(openCodePath); err == nil && info.Mode()&os.ModeSymlink == 0 && !force {
		return fmt.Errorf("refusing to overwrite existing OpenCode skill %s; use workdeck skill install --main %s --force", openCodePath, main)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}
